sudo: required
env:
  global:
    - secure: "ChWhswn18zQ/8RTZXGDUMXj8E66vb8cQbXbbgvOKOAVr9CDHSjipRPtt36azohaWRnwJ8dcZyuWH1RmiQWDEUG9p1oh4kDZUGJYXQpTcWDbnqEzl11A8oGGqlThVC/LUGslLjN9LzaiWHLSTjZL1hB/g7S8QNhcY4DrA5g2klgsDN9/1wvzXH80W+mGv3Vmj7Cxt819BmYQ7c4VCWLzJU2GO1eR2wNqjxDn4cX9JY3XzkvKqSLFNy66OJxeVN8L8jw/GyytsYsTqe7j1mxeqiXhwoJXWilCUi3KnutyqrCwbYrabm0MiduVDlWc+uWPsLIrvlnYgVGaW3fPrqj1ese+fhrCgXHtqAvGlAIIG0HwYD8TqBmo8JNUT5OCiyu+MiTIIVYqyr/ms5AXavJYl+qmY3Z35FXiOGuLlKeMWnOj+KyUc9DHyZh9CaQR96Go7Sq1MmAktwWpS1DTqZEOHusN9rb4u8clXQdmbcTr7MQgct0n9LSxzBXyiua1vNXGMAkMtGP+a6BXM+22VTIIfWWHrv8Ze/lq7nMOkOrewVU0Qfa5Gg+Nl2y6ZhodDkSGYBiuMPWJUAGh1mKdr7HN/LBjxwVqSLQRW6zZ94FNPP7HP5XXPimFhxtdoIZ7mTfBXqunYzGqyOiojdTvPBSGB4rO4oK7rxTgZkYinKcLkst8="
services:
  - docker
before_install:
  - docker pull ros:indigo-robot
script:
  - echo $GH_
  - docker run -v `pwd`:/workspace ros:indigo-robot /workspace/build.sh